# Generated by Django 3.2.6 on 2021-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=10)),
                ('master_category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('article_type', models.TextField(default='', max_length=150)),
                ('base_colour', models.CharField(default='', max_length=50)),
                ('season', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('usage', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(default='', max_length=300)),
                ('price', models.CharField(max_length=200)),
                ('discount_price', models.CharField(max_length=200)),
                ('brand_name', models.CharField(default='', max_length=50)),
                ('age_group', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
