# Generated by Django 3.2.6 on 2021-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211002_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_view',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
