# Generated by Django 3.2 on 2021-07-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
