# Generated by Django 3.2.6 on 2021-10-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_view_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_view',
            new_name='Product',
        ),
    ]
